In [66]:
import numpy as np


arr = np.array([
    [[1, 2],
      [3, 4]],
    [[5, 6],
      [7, 8]]
    ])

print(arr.shape) # shape: (2, 2 ,2)
print(arr[1, 0, 1])  # Output: 6
print(arr[1][0][1])  # Output: 6


(2, 2, 2)
6
6


In [67]:


print(arr[0, 0, :])  


print(arr[1, :, 1]) 


print(arr[:, :, 0]) 

[1 2]
[6 8]
[[1 3]
 [5 7]]


In [68]:

reshaped_arr = arr.reshape(4, 2)
print(reshaped_arr)
print()

transposed_arr = arr.transpose()
print(transposed_arr)
print()

flattened_arr = arr.flatten()
print(flattened_arr)
print()


mask = (arr[:, :, :] > 5)
doublemask = (arr[:, :, :] > 5) | (arr[:, :, :] < 4)
masked_arr = arr[mask]
doublemasked_arr = arr[doublemask]
print(masked_arr)
print()
print(doublemasked_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]

[1 2 3 4 5 6 7 8]

[6 7 8]

[1 2 3 6 7 8]
